### PR TITLE
Direct Data Target extension "Overwrite selection"

### PR DESCRIPTION
**Pull request by woellundwoell**
Select Overwriting for DataTarget "Direct"

- If source is empty
- If target is not empty

### CODE REVIEW

**Comment by woellundwoell** [comment]
recheck

**Comment by fashxp** [comment]
@woellundwoell please post the phrase 'I have read the CLA Document and I hereby sign the CLA' in a comment to make the CLA happy :)

**Comment by woellundwoell** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mcop1** [comment]
Thanks again 👍

**Pull request merged**
