### PR TITLE
[Improvement] Add an options to disable info logs for parallel and sequential import commands

### LINKED ISSUE #79: Possibility to control the logging in Application Log
Each record that is processed, an entry is added in Application Log. 
This becomes redundant in scenarios where feeds are large volumes and imported daily in full.
As suggestion, I would propose to have better control on Application Log (e.g. either log errors only, or log all)

### PR DESCRIPTION
**Pull request by SamyMP**
resolves #79 

I don't know if this is the way to go about this, but it works. To disable info logs during imports, add the --no-logs

For example : 
```bash
bin/console datahub:data-importer:process-queue-parallel --no-logs
```

### CODE REVIEW

**Comment by SamyMP** [comment]
recheck

**Comment by SamyMP** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mcop1** [comment]
Hello @SamyMP ,
thank you for opening the pr. I agree with you, data-imporer needs some kind of log-level or log activate/deactive functionality. But it may be a bit confusing to just add this to the command. Additionally the option is called "no-logs", but, for example, error logs would still be generated. 

I would prefer to have that option somewhere in the configuration, maybe below the "activate" checkbox in the general tab. Then, of course, we would have to check the bundle for log/error messages and output them according to this option. We could create a helper class/service for that. 

What do you think?

**Comment by mcop1** [comment]
Hello @SamyMP , 
any chance you had some time to look at my comment?

**Comment by SamyMP** [comment]
Hi @mcop1,

I missed it, sorry 😅
I agree with you about the name of the option, it might not be the best. According to your suggestion, it could be `--no-info-logs` and `no-error-logs`, something among those lines. Feel free to suggest a name if you think of better ones.
About the way I implemented it, it is true that it is a bit confusing and it deserves a proper way to configure it (with the UI...), but I was aiming for a quick and easy solution.

The service would definitly be the way to go. I don't know if I would be able to do it though, this is one of my first pull requests. Maybe with some guidance ? I would appreciate some help :)

**Pull request closed without merging**
