### PR TITLE
Fixed a bug that Quantityvalue Operator result can be null

### PR DESCRIPTION
**Pull request by aweichler**
Fixed a bug that caused quantity fields to be empty but with units. In addition, an empty string is no longer converted to 0. In both cases NULL is used.

### CODE REVIEW

**Comment by mcop1** [comment]
@aweichler could please have a look at the failing test?

**Comment by aweichler** [comment]
@mcop1 I see the failing test.
What I wanted to achieve, that quantity values can be "null" if no unit and no value are included, cannot work because the test always expects a quantity value.
What do you think, would it be right to allow null values? If so, then the test would have to be adapted. If not, then I close the pull request.

**Comment by mcop1** [comment]
@aweichler since other operators already return `null`, I don´t see a problem with extending the return tag to allow `null`

**Comment by fashxp** [comment]
@aweichler 
Hmm, I'm not entirely sure about that one. 
I think, there could be use cases where you want to import the unit, but don't have a value yet. that would not be possible anymore with that change. 
So, I also checked for the unit to be set before returning null ... but there I'm not sure, if that is still what you want to archive?

**Comment by aweichler** [comment]
There are 2 thing I wanted to achive.
The first is I want the Quantity Value be null if there is no value.
Would it be fine to integrate a checkbox "set unit null if no value"?
So we do not have a BC.

The second thing what I wanted to achive was the following:
If there is no value and no unit in the data source (an empty cell) and the Operator is set to "Unit Abbreviation" the value gets converted to 0. The changes in this PR fixes this.
For example if you have a temperature field, empty is not the same like 0 °C.

**Comment by fashxp** [comment]
> The first is I want the Quantity Value be null if there is no value.
> Would it be fine to integrate a checkbox "set unit null if no value"?

Yes, I guess we need an checkbox there. Would you like to adapt the PR? Thx very much!

**Comment by fashxp** [comment]
@aweichler ping :)

**Comment by aweichler** [comment]
Sorry for the late answer, I am very busy at the moment. But I added the checkbox :)

**Comment by fashxp** [comment]
thx very much for your contribution. I added some tests and combined it into  #196 (your credits for the changes remain in tact of course).

**Comment by fashxp** [comment]
fixed via #196

**Pull request closed without merging**
