### PR TITLE
[Feature]: Transformation Pipeline QuantityUnit "by unit abbreviation" + "with static unit"Quantity value

### PR DESCRIPTION
**Pull request by woellundwoell**
Extends the transformation pipeline "quantityValue" with tho following features:

- Import the unit by abbreviation
- Import quantityValue with pre selected static unit

### CODE REVIEW

**Comment by fashxp** [comment]
recheck

**Comment by fashxp** [comment]
recheck

**Comment by woellundwoell** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mcop1** [comment]
thank you 👍

**Pull request merged**
