### PR TITLE
[Feature] Add SQL Data Source

### PR DESCRIPTION
**Pull request by msoroka**
Originally created by [LemonMind](https://lemonmind.com) and [TorqIT](https://www.torqit.ca/) on [Data Importer Extension](https://github.com/TorqIT/data-importer-extensions-bundle).

All explained in attached docs.

### CODE REVIEW

**Comment by mattamon** [comment]
Hey @msoroka

Unfortunately the static analysis failed, could you please recheck your code and fix the tests.

**Comment by mattamon** [comment]
Hey @msoroka are you still working on this? It seems like a pretty cool feature, but with failing tests we cannot merge it. 

Could you give me a quick comment, that you are going to fix this? Otherwise I will close the PR in a week. If you still want this, we can reopen the PR anytime then.

**Comment by msoroka** [comment]
@mattamon Yes, I'll do it till end of this week.

**Comment by mattamon** [comment]
> @mattamon Yes, I'll do it till end of this week.

Awesome thank you!

**Comment by msoroka** [comment]
@mattamon Done

**Review by mattamon — CHANGES_REQUESTED** [review]
I checked out and tested the PR now. 
Thank in advance! It looks pretty solid and is a neat feature! 

Works like expected at least for my tests. One minor change, could you please add the `declare(strict_types=1);` to every php file.

**Review by mattamon — APPROVED** [review]
Looks good to me! Thanks for your patience and time!
Really appreciate this new feature!

**Pull request merged**
