### PR TITLE
Config Name Limit Increase

### PR DESCRIPTION
**Pull request by shamoh19**
Follow Up fix for below improvement/bug for #99

### CODE REVIEW

**Comment by shamoh19** [comment]
recheck

**Comment by shamoh19** [comment]
recheck

**Comment by shamoh19** [comment]
recheck

**Comment by shamoh19** [comment]
recheck

**Comment by shamoh19** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by gpariya — APPROVED** [review]
This looks fine.

**Comment by mcop1** [comment]
Thank you :)

**Pull request merged**
