### PR TITLE
Fixed ApplicationLogger namespaces

### PR DESCRIPTION
**Pull request by kkarkus**

### CODE REVIEW

**Comment by kkarkus** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kkarkus** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by kkarkus** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kkarkus** [comment]
recheck

**Comment by Corepex** [comment]
@kkarkus, thanks for creating a PR :partying_face: 

Since the `data-importer` still supports [10.6](https://github.com/pimcore/data-importer/blob/1.x/composer.json#L24), we can`t change the namespace here because doing so would break the 10.6 installations. (see the failing test)

**Pull request closed without merging**
