### PR TITLE
[New Feature] Data target extension for advanced relations

### PR DESCRIPTION
**Pull request by woellundwoell**
- DirectDataTarget can handle advanced relations
- Option "append / merge relation items"

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by fashxp** [comment]
I would prefer to have an own data target `ManyToManyRelation` instead of packing all that functionality into the `Direct` data target. 

Because now all preprocessing is done for all the attributes - and besides that `$definition->getFieldDefinition($attributeName);` will not always return a field definition, e.g. for object brick attributes and I'm also not sure about localized attributes. 

Having an own data target also would allow us to add more specific assigment features in the future, e.g. `removeItems`

Could you update your PR accordingly?

**Comment by woellundwoell** [comment]
We thought it was a good idea to integrate the functionality in the DirectDateTarget. ;)
But OK, we will separate it into a M2MRelationDataTarget and provide a PR.

**Comment by woellundwoell** [comment]
The main reason why we decided to implement it this way was that otherwise an extra operator is needed to identify a new TransformationDataType in a "ManyToManyRelationDataTarget".
What Du you think?

**Comment by woellundwoell** [comment]
Another possibility would be to move all relation imports into a new DataTarget. So we don't need an extra Operator.
But this would break existing settings for manyToManyRelation imports...

**Pull request merged**
