### PR TITLE
Fix wrong relation loading response

### LINKED ISSUE #158: [Bug]: Simple data_object loader should return array instead of DataObject-Class
### Expected behavior

If I want to import a relation within a class and use Load Data Objects -> with Attributes it should insert the relation into Data Object.

### Actual behavior

No relations are imported

### Steps to reproduce

1. Create two classes, with one having a relation to the second class
2. Create csv-file that cna load objects from one class
3. Setup the importer to load the dataobjects accordingly
4. Import

Following files may help (remove the .txt to get the files to work):
[import_dealer.yaml.txt](https://github.com/pimcore/data-importer/files/7972468/import_dealer.yaml.txt)
[cardealers.csv](https://github.com/pimcore/data-importer/files/7972474/cardealers.csv)
[definition_CarsDealer.php.txt](https://github.com/pimcore/data-importer/files/7972482/definition_CarsDealer.php.txt)
[definition_CarsManufacturer.php.txt](https://github.com/pimcore/data-importer/files/7972485/definition_CarsManufacturer.php.txt)

### PR DESCRIPTION
**Pull request by florian25686**
#157 
Unfortunately #159 has been closed due to my rebasing :/

I fixed the code that returns a scalar/not array to test if it is an array.

### CODE REVIEW

**Comment by florian25686** [comment]
@fashxp I created a new fix, can you please take a look into this? Appreciate

**Comment by fashxp** [comment]
👍 now fixes the symptom without breaking stuff ... still need to fix the root cause at some point, see https://github.com/pimcore/data-importer/issues/161

thx very much for the contribution.

**Comment by fashxp** [comment]
@florian25686 since this is a bugfix, could you please rebase it to 1.3 branch? 

we would like to release today.

**Comment by florian25686** [comment]
@fashxp Will do asap

**Comment by florian25686** [comment]
@fashxp Done

**Comment by fashxp** [comment]
looks good, thx!

**Pull request merged**
