### PR TITLE
Update SftpLoader.php

### LINKED ISSUE #121: [Bug]: SFTP not working - Could not copy from remote location
### Expected behavior

A Json-File is stored on a SFTP-Server.
When starting the import (manually) the file should be copied from the SFTP-Server in a tmp-folder to load it from there and import the data in pimcore

### Actual behavior

After starting the job, an error ("Could not copy from remote location") appears

### Steps to reproduce

1. setup a SFTP-Server with username and password login and a dedicated folder for the sftp (e.g. /var/sftp/uploads/)
2. fill in the login-data to the data-importer "Data Source" form, use type=SFTP and Format JSON
3. store a json-file (e.g. products.json) on the folder /var/sftp/uploads
4. set the remote path absolute (e.g. /var/sftp/uploads/products.json) or relative (/uploads/products.json)
5. start the job

### PR DESCRIPTION
**Pull request by Daniel-Ateles**
Downloads the sftp stream to the local file and returns the file.

### CODE REVIEW

**Comment by Daniel-Ateles** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Daniel-Ateles** [comment]
recheck

**Comment by fashxp** [comment]
@Daniel-Ateles could you please rebase to 1.3 branch as this is a bugfix. Thx.

**Comment by fashxp** [comment]
@Daniel-Ateles ping :)

**Comment by Daniel-Ateles** [comment]
> @Daniel-Ateles could you please rebase to 1.3 branch as this is a bugfix. Thx.

Should I select "origin/1.3" or "upstream/1.3" (see screenshot)
image

**Comment by fashxp** [comment]
if your origin is quite up-to-date is should not matter.

**Comment by Daniel-Ateles** [comment]
> if your origin is quite up-to-date is should not matter.

There were no changes to rebase for origin/1.3 but 12 on the upstream, so I selected upstream and solved some merge conflicts. So it should be done now.

**Comment by fashxp** [comment]
hmm, still not able to change the base to 1.3 properly. 
maybe just create a new PR starting already from 1.3 branch?

**Comment by fashxp** [comment]
it seems, you merged 1.x somehow into that branch. It think start over again would be the easiest and fastest option.

**Comment by Daniel-Ateles** [comment]
> it seems, you merged 1.x somehow into that branch. It think start over again would be the easiest and fastest option.

Ok! Will do!

**Comment by Daniel-Ateles** [comment]
> hmm, still not able to change the base to 1.3 properly. maybe just create a new PR starting already from 1.3 branch?

Done. I've created a PR for "sftploader-fix-3" based on 1.3.

**Comment by fashxp** [comment]
closed in favor of #155

**Pull request closed without merging**
