### PR TITLE
Fix 0 index for attribute-based strategy

### LINKED ISSUE #202: [Bug]: Empty data source index exception if index is 0
### Expected behavior

I can point any column from xlsx/csv data file as source to the attribute-based Element Publishing strategy.

### Actual behavior

I have a data-file with "Active" attribute in first column. This column (from processor's point of view) has index "0".
In the attribute-based Element Publishing strategy I pointed on this column but when I'm trying to run import I get `Pimcore\Bundle\DataImporterBundle\Exception\InvalidConfigurationException` with 'Empty data source index' message.

It happens because of this part of code (`Pimcore\Bundle\DataImporterBundle\Resolver\Publish\AttributeBasedStrategy` class):
```php
if (empty($settings['dataSourceIndex'])) {
    throw new InvalidConfigurationException('Empty data source index.');
}
```

I believe this `if` expression should be like this:
```php
public function setSettings(array $settings): void
{
    if (($dsi = $settings['dataSourceIndex'] ?? null) === null) {
        throw new InvalidConfigurationException('Empty data source index.');
    }

    $this->dataSourceIndex = $dsi;
}
```

### Steps to reproduce

Try to import any xlsx/csv file with 'published' attribute in very first column and use attribute-based Element Publishing strategy.

### PR DESCRIPTION
**Pull request by andrew72ru**
Closes #202

### CODE REVIEW

**Comment by andrew72ru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by robertSt7** [comment]
@andrew72ru could you please rebase the PR to 1.5?

**Comment by andrew72ru** [comment]
> @andrew72ru could you please rebase the PR to 1.5?

I've tried but I'm not sure that I did it properly… Take a look please

**Comment by robertSt7** [comment]
@andrew72ru It looks like that didn't work. Could you please just create a new PR with the right base?

**Comment by andrew72ru** [comment]
Sure, this is not a problem

**Pull request closed without merging**
