### PR TITLE
Added PackageVersionTrait for getting Bundle version

### PR DESCRIPTION
**Pull request by vmalyk**

### CODE REVIEW

**Comment by fashxp** [comment]
@vmalyk  haha, the obligatory Vladimir PR 😉 
thanks man! Could you please rebase to 1.0 branch and make the CLA happy.

**Comment by vmalyk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vmalyk** [comment]
@fashxp , I see 1.x branch as main and 1.1 as unmerged. So, should i use 1.1 as base?

**Comment by fashxp** [comment]
ah, sorry ..1.1 I meant ... since I would classify that as bugfix :-)

**Comment by vmalyk** [comment]
@fashxp , updated  and ready for approval ;)

**Pull request merged**
