### PR TITLE
Fix wrong relation loading response

### LINKED ISSUE #158: [Bug]: Simple data_object loader should return array instead of DataObject-Class
### Expected behavior

If I want to import a relation within a class and use Load Data Objects -> with Attributes it should insert the relation into Data Object.

### Actual behavior

No relations are imported

### Steps to reproduce

1. Create two classes, with one having a relation to the second class
2. Create csv-file that cna load objects from one class
3. Setup the importer to load the dataobjects accordingly
4. Import

Following files may help (remove the .txt to get the files to work):
[import_dealer.yaml.txt](https://github.com/pimcore/data-importer/files/7972468/import_dealer.yaml.txt)
[cardealers.csv](https://github.com/pimcore/data-importer/files/7972474/cardealers.csv)
[definition_CarsDealer.php.txt](https://github.com/pimcore/data-importer/files/7972482/definition_CarsDealer.php.txt)
[definition_CarsManufacturer.php.txt](https://github.com/pimcore/data-importer/files/7972485/definition_CarsManufacturer.php.txt)

### PR DESCRIPTION
**Pull request by florian25686**
Fixes https://github.com/pimcore/data-importer/issues/158

### CODE REVIEW

**Comment by florian25686** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by florian25686** [comment]
recheck

**Comment by fashxp** [comment]
I'm pretty sure, that this is not the right fix, as it now returns an array when the response should be a scalar.

**Comment by florian25686** [comment]
There is already a problem in the input, if $input is not an array, which in my case it is not, it will set `$returnScalar` to true where it should be false.
I think that, wether the loading of dataobjects is wrong somehow or this function.

Unfortunately I wasn't able to find any advanced documentation on how to use the `Load Dataobject` in combination with an actual data object class.

**Comment by florian25686** [comment]
Going down the :rabbit: whole and digging deeper:
1. Unintended type-conversion in a return due to not validated input
     With the provided example you'll find that `get_class($data)` returns `Pimcore\Model\DataObject\CarsManufacturer`

     In [getMergedDataArray()](https://github.com/pimcore/data-importer/blame/1.x/src/Mapping/DataTarget/ManyToManyRelation.php#L88) `$data` does not have a type, yet the function returns an array
    ```php
     protected function getMergedDataArray($valueContainer, string $getter, string $fieldType, $data)
    ```
    For my case this has the [wrong returntype](https://github.com/pimcore/data-importer/blame/1.x/src/Mapping/DataTarget/ManyToManyRelation.php#L112)
    ```php
     else {
          return $data;
     }
     break;
    ```
    See the image currently holding not an array but directly the object
error_debugging

**Comment by fashxp** [comment]
mhm, I see ... I would see the problem even one step earlier ... the data target manyToMany relation should only be allowed when having asset/object array as transformation result and/or the `doAssignData` needs to make sure. that `$data` is an array.

**Pull request closed without merging**
