### PR TITLE
SftpLoader fix. 

### PR DESCRIPTION
**Pull request by Daniel-Ateles**
Made the SftpLoader download the file and return it instead of copying it within the sftp and not returning anything.

### CODE REVIEW

**Comment by Daniel-Ateles** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Daniel-Ateles** [comment]
recheck

**Review by Daniel-Ateles — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Review by Daniel-Ateles — COMMENTED** [review]
recheck

**Comment by NiklasBr** [comment]
You made [your commit](https://patch-diff.githubusercontent.com/raw/pimcore/data-importer/pull/145.patch) with your `@cag.se` address, have you added it to your GitHub account?

**Comment by Daniel-Ateles** [comment]
I have made a new branch/PR. This can be rejected/removed.

**Pull request closed without merging**
