### PR TITLE
Set classification store data in importing elements

### LINKED ISSUE #69: [Classification Store] Conflict with class Inheritance setting
When I am trying to import data into nested product objects, data doesn`t save correctly.
For example, I have two key definitions (text input) in one group of Classification Store, mapped by import configuration. 
Firstly, I imported ParentItem1 with non empty values and imported two child items with other values for key definitions after few days. When I opened a child product, I saw the data from the parent in grayed out fields instead of the imported ones. The data in the database table was also not saved.

Objects Tree:

```
|- ParentItem1
|-- ChildItem1
|-- ChildItem2
```

Product class has "Allow inheritance" option checked.

### PR DESCRIPTION
**Pull request by msoroka**
Linked issue: [69](https://github.com/pimcore/data-importer/issues/69)

Solves the problem with import classification store for the "Find parent" strategy in "Element Creation" resolver with inheritance enabled in same classes for both parent and child.

### CODE REVIEW

**Comment by msoroka** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fashxp** [comment]
since this is a bugfix, can you please rebase to 1.3 branch

**Comment by msoroka** [comment]
@fashxp done

**Comment by fashxp** [comment]
please don't merge, this is not a proper fix as it breaks the inheritance of classification store fields. 
there is a  underlying problem in pimcore. 
see also https://github.com/pimcore/pimcore/pull/11270

**Pull request closed without merging**
