### PR TITLE
[DOCS] Add install command to documentation

### PR DESCRIPTION
**Pull request by jorisros**

### CODE REVIEW

**Comment by Corepex** [comment]
@jorisros, thanks for your PR. Could you please accept the CLA - after that I could merge your docs improvement. 👍

**Comment by jorisros** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jorisros** [comment]
Request Comment same as the below format.

I have read the CLA Document and I hereby sign the CLA

You can retrigger this bot by commenting recheck in this Pull Request

**Comment by jorisros** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Corepex** [comment]
@jorisros could you please merge the `pimcore/data-importer` 1.x branch into your PR to resolve the codeception tests.

**Comment by Corepex** [comment]
@jorisros friendly reminder - have you seen my comment above?

**Comment by Corepex** [comment]
Will create a new PR to get the change done (will base the PR on the bugfix branch)

**Comment by Corepex** [comment]
@jorisros created a new PR and added you as my coauthor (#285) 😉

**Pull request closed without merging**
