### PR TITLE
[BUGFIX] fix date mapping

### PR DESCRIPTION
**Pull request by dpfahlbusch**
create carbon instead of datetime instance for correct import

https://github.com/pimcore/pimcore/discussions/9787 as discussed and solved here :)

### CODE REVIEW

**Comment by dpfahlbusch** [comment]
recheck

**Comment by fashxp** [comment]
Thx for the PR! Please type the phrase 'I have read...' to make CLA happy!

**Comment by dpfahlbusch** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dpfahlbusch** [comment]
recheck

**Comment by fashxp** [comment]
thx

**Pull request merged**
