### PR TITLE
Add execution schedule types

### LINKED ISSUE #128: [Improvement]: Converting Cron Definition to datetime (dd-mm-yyyy hh:mm)
### Improvement description

Add the possibility to set a specific datetime (dd-mm-yyyy hh:mm) by using the datepicker as an extra option to a cron definition within the configuration settings.

We can give options to user either to choose cron definition or choose date/time from the picker. Internally we should handle the configuration accordingly

DatePicker_Open

### PR DESCRIPTION
**Pull request by flamadrid-jsmdg**
Resolves #128
Add additional option to schedule imports for a specific point in time.

- [x] Wait for #122 to be merged and test migrations.
- [x] It fixes the issue addressed in https://github.com/pimcore/data-importer/pull/109 but need to re-test after that one is merged. 
- [x] Test edge cases and behavior with pre existing configurations
- [x] Review migrations (base class)
- [x] Review implementation of ExecutionService::initExecution (table might not exists.)

### CODE REVIEW

**Comment by dvesh3** [comment]
> Fix migrations not executing? Does it need a installer?

@flamadrid-jsmdg yes, we added an installer in https://github.com/pimcore/data-importer/pull/122/files#diff-67306479da293f095927542c4cff1a45875138eb52372caaba982b07c053285b so it should execute migrations once this is merged.

**Comment by ghost** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by flamadrid-jsmdg** [comment]
Fixes #128 #

**Comment by fashxp** [comment]
@flamadrid-jsmdg  https://github.com/pimcore/data-importer/pull/122 is finally merged ... so this one should also be ready to be continued. 
Thx very much!

**Comment by mcop1** [comment]
Great work, thanks!

**Pull request merged**
